timezone: Asia/Shanghai

name: Arthur.Qin
permalink: /blog/:year/:month/:day/:title

# Multiple languages
gems: ['jekyll-paginate', 'jekyll-multiple-languages']

languages: ['en', 'cn']

# If not config, the first of languages will be the default
language_default: 'en'
